version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:9090 run:app
    ports:
      - 9090:9090
    environment:
      - FLASK_ENV=development
      - DB_USER=root
      - DB_HOST=db
      - DB_PORT=27017
      - DB_PASSWORD=rootpassword
    volumes:
      - .:/usr/src/web
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
