version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 run:app
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=production
      - DB_USER=root
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=main
      - DB_PASSWORD=rootpassword
    volumes:
      - .:/usr/src/web
    db:
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
