version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run.py
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - DB_USER=root
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=main
      - DB_PASSWORD=rootpassword
    volumes:
      - .:/usr/src/web
    links:
      - db
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
